### ISSUE TITLE
Using ready results or running the simulations for obtaining data 

### ISSUE THREAD

**Issue by ddimoski** [Notebook-Factory/RRIFT_notebooks#1]
Hi,

We noticed that there are 2 ways to obtain the data we need for plotting the figures (explained in the readme file in the paper repo) - one is by running the simulations ourselves which will produce the files with the needed data, and the other option is by using the already generated result files in the [OSF repository](https://osf.io/wr3kf/files/). 

Is there a preference over which method we should use to obtain the data?

**Comment by mathieuboudreau** [comment]
Do the easiest (in terms of implementation) and quickest (in terms of computational speed) way first (so I think that will be the OSF repository method). If you have time, we can plan the best way to let the users know that reproducing the simulations is also a possibility and possibly integrate that in that (or another) notebook. But do the easiest way first.

**Comment by zelenkastiot** [comment]
I would have to agree with @mathieuboudreau on this one hence he has more experience with data usage. 
The OSF method is faster and you wouldn't have to spend too much time on it.

**Comment by ddimoski** [comment]
Got it, thanks for the help :)

**Comment by agahkarakuzu** [comment]
@ddimoski did you find/implement a solution that works for you?

**Comment by ddimoski** [comment]
@agahkarakuzu yes, I'm closing this issue.
