### ISSUE TITLE
Figure-2 and Figure-3 legends are not grouped

### ISSUE THREAD

**Issue by agahkarakuzu** [Notebook-Factory/RRIFT_notebooks#5]
When you try isolating a trace across the (sub)panels, it only takes effect for the third one. Can try grouping the legends so that when we interact with one of them, traces across the panels are updated:

![image](https://user-images.githubusercontent.com/9632322/107050157-e6cfcc80-6798-11eb-8bd6-1636f14b4945.png)

For example, when dark-blue trace (5) is double clicked, it should be isolated on all the panels. 

You can see the first example here: 

https://plotly.com/python/legend/

**Comment by emorevival** [comment]
Hi, we have fixed them, should work as expected now.
